USE [Teste]
GO
IF OBJECT_ID('dbo.P_CFOP_GROUP') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_CFOP_GROUP
    IF OBJECT_ID('dbo.P_CFOP_GROUP') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_CFOP_GROUP >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_CFOP_GROUP APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE dbo.P_CFOP_GROUP 
AS
BEGIN
	SELECT
		CONCAT(Cfop, '|',
			SUM(BaseIcms), '|',
			SUM(ValorIcms), '|',
			SUM(BaseIpi), '|',
			SUM(ValorIpi), '|'
		) as 'Result'
	FROM
		NotaFiscalItem
	GROUP BY 
		Cfop
END
GO
GRANT EXECUTE ON dbo.P_CFOP_GROUP TO [public]
IF OBJECT_ID('dbo.P_CFOP_GROUP') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_CFOP_GROUP CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_CFOP_GROUP >>>'
go